# Generated by Django 2.2.5 on 2021-04-21 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20210420_1345'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='room',
            table='rooms',
        ),
    ]
